env:
  node: true
  browser: true
  es2021: true

extends:
  - plugin:react/recommended
  - airbnb

parser: "@babel/eslint-parser"  

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - babel

rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
